### ISSUE TITLE
local updates for supsect clients

### ISSUE THREAD

**Issue by stha-prashant** [Eyr3/FLTracer#1]
Hi, can you please share the local updates used in the paper?

**Comment by QingyuLiu** [comment]
Sure, we share [links](https://pan.baidu.com/s/1CGUfjILsscq9XWpehSygcg?pwd=tykw) to the 10 local updates for an epoch and their reference updates. You need to place the compressed file in the project directory and unzip it. Remember to modify the parameters in the `blind_backdoor_detect.yaml` file to ensure that the updates can be read successfully.
